dist: bionic
language: cpp

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - llvm-10-dev
      - libclang-10-dev

script:
  - ./build.sh
